DROP TABLE IF EXISTS "customers_dim" CASCADE;
CREATE TABLE "customers_dim" (
	"customer_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"phone" VARCHAR(255) NOT NULL,
	"valid_until" DATE
);
DROP INDEX IF EXISTS IX_customers_dim_customer_id;
CREATE INDEX IX_customers_dim_customer_id ON customers_dim (customer_id);



DROP TABLE IF EXISTS "products_dim" CASCADE;
CREATE TABLE "products_dim" (
	"product_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"product_name" VARCHAR(255) NOT NULL,
	"category" VARCHAR(255) NOT NULL,
	"valid_until" DATE
);
DROP INDEX IF EXISTS IX_products_dim_product_id;
CREATE INDEX IX_products_dim_product_id ON products_dim (product_id);



DROP TABLE IF EXISTS "sales_fact" CASCADE;
CREATE TABLE "sales_fact" (
	"sale_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"customer_id" INTEGER NOT NULL,
	"product_id" INTEGER NOT NULL,
	"sale_date" DATE NOT NULL,
	"amount" DECIMAL NOT NULL,
	"quantity" INTEGER NOT NULL,
	PRIMARY KEY("sale_id")
);

DROP INDEX IF EXISTS IX_sales_fact_customer_id;
CREATE INDEX IX_sales_fact_customer_id ON sales_fact (customer_id);

DROP INDEX IF EXISTS IX_sales_fact_product_id;
CREATE INDEX IX_sales_fact_product_id ON sales_fact (product_id);
